import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Header
    'nav.home': 'Home',
    'nav.collection': 'Coleção',
    'nav.shop': 'Loja',
    'nav.battle': 'Batalha',
    'nav.farm': 'Farm',
    'nav.whitelist': 'Mint',
    'nav.community': 'Comunidade',
    'nav.connect': 'Conectar Carteira',
    
    // Hero
    'hero.title': 'Pudgy Farms',
    'hero.subtitle': 'Começamos com a coleção Pudgy Chickens - a primeira tokenização de galinhas REAIS do mundo! Cada colecionável pode ser trocado por uma galinha física real, dependendo da disponibilidade e região. Projeto totalmente open-source.',
    'hero.info.title': 'Sobre os Colecionáveis',
    'hero.info.description': 'Os Pudgy Chickens são colecionáveis digitais que representam produtos reais (galinhas ou ovos). Este é um produto de coleção, não um investimento financeiro. Cada colecionável pode ser trocado por uma galinha física real, sujeito à disponibilidade e região. Os Eggs (ovos) também podem ser trocados por ovos reais quando disponíveis.',
    'hero.info.disclaimer': '⚠️ Importante: Este é um produto de coleção, não um investimento. O ativo representa um produto físico (galinha ou ovos) e pode ser trocado dependendo da disponibilidade e região.',
    'hero.cta.primary': 'Tokenizar seu RWAnimal',
    'hero.cta.secondary': 'Ver Nosso Galinheiro',
    'hero.cta.learnMore': 'Saiba Mais',
    'hero.cta.mint': 'Mint seu PudgyChicken',
    'hero.cta.contact': 'Entre em Contato',
    'hero.stats.chickens': 'Coleção Pudgy Chickens',
    'hero.stats.tokenized': 'Tokenização Real',
    'hero.stats.farms': 'Projeto Educacional',
    'hero.education.title': 'Projeto Colaborativo & Educacional',
    'hero.education.subtitle': 'Curso Completo de Smart Contracts',
    'hero.education.description': 'Este é um projeto colaborativo e educacional que inclui um curso completo sobre os smart contracts de RWA (Real World Assets) desenvolvidos para esta plataforma. Quando atingirmos 1.800 mints, o curso será disponibilizado totalmente gratuito no YouTube para todos! Após ultrapassarmos essa meta, parte do valor arrecadado será destinada a projetos desenvolvidos pelos alunos do curso, pela comunidade e pelas farms do ecossistema.',
    'hero.education.disclaimer': '⚠️ Importante: Este é um projeto totalmente colaborativo, sem expectativa de retorno financeiro. Todos os participantes terão benefícios em tudo que for desenvolvido e produzido nas farms do ecossistema.',
    'hero.education.goal': 'Meta: 1.800 Mints',
    'hero.education.benefits': 'Benefícios Colaborativos',
    'hero.education.benefits.list': '• Curso gratuito no YouTube\n• Parte do valor para projetos da comunidade\n• Benefícios em todas as farms do ecossistema\n• Participação em projetos desenvolvidos\n• Comunidade colaborativa de desenvolvedores',
    
    // Detailed Description
    'hero.detailed.description': 'A PudgyFarm representa uma revolução completa no ecossistema Web3 brasileiro, combinando tokenização de ativos reais, gamificação educacional e desenvolvimento sustentável da agricultura. Os holders terão benefícios exclusivos em todas as tokenizações futuras da PudgyFarm, incluindo produtos e animais reais e seus insumos, com a única restrição sendo a disponibilidade regional. Nossa plataforma é totalmente interativa, permitindo batalhas entre colecionáveis onde você pode vencer mesmo com ativos menos raros, baseado em histórico de vitórias e interação com o ecossistema. Quanto mais ativo e engajado você for, maior será sua reputação, proporcionando ainda mais benefícios e chances de vitória. Além das batalhas, você pode contribuir com PudgyEggs, representação digital dos ovos reais das galinhas. A PudgyFarm oferece um sistema de tokenização próprio, permitindo que qualquer pessoa digitalize seus animais reais sem conhecimento técnico de blockchain, participando de todo o ecossistema e seus benefícios. É um ecossistema completo: tokenização de ativos reais, colecionáveis com raridades e habilidades únicas, sistema de reputação, batalhas justas e representação digital dos ovos reais das galinhas. Tudo isso apoiado por um curso educacional com o objetivo de formar mais desenvolvedores e impulsionar o crescimento do ecossistema Web3 no Brasil. Participe da whitelist e faça parte desta "Revolução dos Bichos Web3" focada em crescimento econômico e educacional.',
    
    // Details Page
    'details.backToHome': 'Voltar ao Início',
    'details.title': 'Revolução dos Bichos Web3',
    'details.subtitle': 'Descubra como a PudgyFarm está transformando o agronegócio brasileiro através da tecnologia blockchain e tokenização de ativos reais.',
    'details.features.title': 'Funcionalidades Principais',
    'details.features.subtitle': 'Um ecossistema completo que combina tecnologia, educação e sustentabilidade',
    'details.features.realAssets.title': 'Tokenização de Ativos Reais',
    'details.features.realAssets.description': 'Cada NFT representará um animal no mundo real em nosso ecossistema, conectando o mundo digital ao físico.',
    'details.features.community.title': 'Comunidade Premium',
    'details.features.community.description': 'Acesso exclusivo a benefícios, produtos reais e participação em decisões da comunidade.',
    'details.features.battles.title': 'Sistema de Batalhas',
    'details.features.battles.description': 'Batalhe com outros colecionáveis em um sistema justo baseado em reputação e estratégia.',
    'details.features.eggcoin.title': 'PudgyEggs - Ovos Reais',
    'details.features.eggcoin.description': 'Representação digital de ovos reais das galinhas. Cada PudgyEgg pode ser trocado por ovos frescos das farms do ecossistema, dependendo da disponibilidade e região.',
    'details.features.reputation.title': 'Sistema de Reputação',
    'details.features.reputation.description': 'Quanto mais ativo e engajado, maior sua reputação e chances de vitória nas batalhas.',
    'details.features.education.title': 'Formação Educacional',
    'details.features.education.description': 'Curso completo sobre os smart contracts desenvolvidos. Ao alcançarmos 1.800 mints, o curso será totalmente gratuito para todos os holders!',
    'details.education.title': 'Projeto Colaborativo & Educacional: Curso de Smart Contracts',
    'details.education.subtitle': 'Aprenda com os contratos reais desenvolvidos para o projeto',
    'details.education.description': 'Este é um projeto colaborativo e educacional que visa formar desenvolvedores Web3 no Brasil. Incluímos um curso completo sobre os smart contracts desenvolvidos especificamente para o Pudgy Farms, cobrindo desde conceitos básicos até implementações avançadas. O curso será disponibilizado totalmente gratuito no YouTube.',
    'details.education.goal.title': 'Meta: 1.800 Mints = Curso Gratuito',
    'details.education.goal.description': 'Ao atingirmos a marca de 1.800 mints dos colecionáveis, o curso completo será disponibilizado totalmente gratuito no YouTube para todos!',
    'details.education.funds.title': 'Após 1.800 Mints: Investimento na Comunidade',
    'details.education.collaborative.title': 'Projeto Totalmente Colaborativo',
    'details.education.collaborative.description': 'Este é um projeto totalmente colaborativo, sem expectativa de retorno financeiro. Todos os participantes terão benefícios em tudo que for desenvolvido e produzido nas farms do ecossistema. O foco está na educação, desenvolvimento da comunidade e crescimento sustentável do ecossistema Web3 brasileiro.',
    'details.education.funds.title': 'Após 1.800 Mints: Investimento na Comunidade',
    'details.education.funds.description': 'Quando passarmos de 1.800 mints, parte do valor será destinado a:',
    'details.education.funds.list': '• Projetos desenvolvidos pelos alunos do curso\n• Iniciativas da comunidade\n• Desenvolvimento e manutenção das farms do ecossistema\n• Novos conteúdos educacionais\n• Expansão do projeto colaborativo',
    'details.education.goal.current': 'Mints Atuais',
    'details.education.goal.target': 'Meta',
    'details.education.benefits.title': 'Benefícios para Holders e Jogadores',
    'details.education.benefits.holders': 'Para Holders:',
    'details.education.benefits.holders.list': '• Curso completo de smart contracts gratuito\n• Acesso exclusivo a novos conteúdos educacionais\n• Prioridade em futuras tokenizações\n• Comunidade premium de desenvolvedores\n• Suporte técnico prioritário',
    'details.education.benefits.players': 'Para Jogadores do Game:',
    'details.education.benefits.players.list': '• Recompensas especiais nas batalhas\n• NFTs exclusivos por participação\n• Ranking premium com benefícios\n• Acesso antecipado a novas funcionalidades\n• Torneios com prêmios educacionais',
    'details.education.cta': 'Participe e Ajude a Alcançar a Meta!',
    'details.ecosystem.title': 'Nosso Ecossistema',
    'details.ecosystem.tokenization.title': 'Tokenização Simplificada',
    'details.ecosystem.tokenization.description': 'Sistema próprio que permite digitalizar animais reais sem conhecimento técnico de blockchain.',
    'details.ecosystem.education.title': 'Educação Web3',
    'details.ecosystem.education.description': 'Curso educacional focado em formar desenvolvedores e impulsionar o crescimento do ecossistema Web3 no Brasil.',
    'details.cta.title': 'Faça Parte da Revolução',
    'details.cta.description': 'Junte-se à primeira plataforma de tokenização de animais reais do mundo e seja parte do futuro do agronegócio.',
    'details.cta.mint': 'Mint seu PudgyChicken',
    'details.cta.explore': 'Explorar Projeto',
    
    // Creator Section
    'details.creator.title': 'Sobre o Criador',
    'details.creator.subtitle': 'Conheça a história por trás do primeiro galinheiro tokenizado',
    'details.creator.name': 'Afonso Dalvi',
    'details.creator.role': 'Criador do Primeiro Galinheiro Tokenizado',
    'details.creator.experience': '7+ anos de experiência em tecnologia',
    'details.creator.description': 'Afonso é o criador do Pudgy Farm, desde pequeno sempre gostou de animais e quando cresceu se apaixonou por tecnologia. Com mais de 7 anos de experiência na área, decidiu juntar essas duas paixões com o objetivo de ajudar o agronegócio mundial e o crescimento do Web3 através de um projeto open-source e desenvolvimento de cursos educacionais.',
    'details.creator.childhood': 'Infância',
    'details.creator.today': 'Hoje',
    
    // Vision Section
    'details.vision.title': 'Nossa Visão',
    'details.vision.ecosystem.title': 'Ecossistema Completo',
    'details.vision.ecosystem.description': 'A PudgyFarm representa uma revolução completa no ecossistema Web3 brasileiro, transformando a educação e o agronegócio através de ativos reais, com gamificação dos ativos e desenvolvimento educacional e da agricultura.',
    'details.vision.benefits.title': 'Benefícios Exclusivos',
    'details.vision.benefits.description': 'Os holders terão benefícios exclusivos em todas as tokenizações futuras da PudgyFarm, incluindo produtos e animais reais e seus insumos, com a única restrição sendo a disponibilidade regional. Nossa plataforma é totalmente interativa, permitindo batalhas entre colecionáveis onde você pode vencer mesmo com ativos menos raros.',
    'details.vision.conclusion.title': 'Revolução dos Bichos Web3',
    'details.vision.conclusion.description': 'É um ecossistema completo: tokenização de ativos reais, colecionáveis com raridades e habilidades únicas, sistema de reputação, batalhas justas e representação digital de ovos atrelada ao valor real. Tudo isso apoiado por um curso educacional com o objetivo de formar mais desenvolvedores e impulsionar o crescimento do ecossistema Web3 no Brasil. As coleções não são investimentos e sim representações digitais com utilidades reais.',
    
    // Animated Section
    'gifs.title': 'GIFs da Coleção',
    'gifs.subtitle': 'Baixe e compartilhe os GIFs animados',
    
    // Collection
    'collection.title': 'Nossas Coleções',
    'collection.subtitle': 'Bem-vindo ao mundo dos Pudgy Chickens, uma plataforma nascida na web3 que promove sustentabilidade, inovação agrícola e comunidade através da tokenização de galinhas reais.',
    'collection.explore': 'Explorar Todas as Coleções',
    'collection.items': 'itens',
    'collection.floor': 'Floor Price',
    'collection.view': 'Ver Coleção',
    'collection.original': 'A coleção original de 10.000 galinhas únicas tokenizadas na blockchain.',
    'collection.lil': '5.000 pintinhos de descendência premium. Pequenos mas promissores.',
    'myNFTs.title': 'Meus NFTs',
    'myNFTs.subtitle': 'Todos os seus Pudgy Chickens em um só lugar — coleção padrão e colecionáveis especiais.',
    'myNFTs.special': 'Especial',
    'myNFTs.collection': 'Pudgy Chickens',
    'myNFTs.viewOnChain': 'Ver na blockchain',
    'myNFTs.empty.title': 'Nenhum NFT ainda',
    'myNFTs.empty.description': 'Conecte sua carteira e faça o mint na página de whitelist para começar sua coleção.',
    'myNFTs.empty.cta': 'Ir para o Mint',
    'myNFTs.rarity.common': 'Comum',
    'myNFTs.rarity.rare': 'Raro',
    'myNFTs.rarity.epic': 'Épico',
    'myNFTs.rarity.legendary': 'Lendário',
    
    // Shop
    'shop.title': 'Loja de Ativos',
    'shop.subtitle': 'Colecione galinhas únicas tokenizadas. Cada ativo é único e possui raridade e características especiais. Comece sua coleção hoje!',
    'shop.buy': 'Comprar',
    'shop.viewAll': 'Ver Todos os Ativos',
    'shop.reviews': 'avaliações',
    'shop.reputation': 'Reputação',
    
    // Community
    'community.title': 'A Comunidade',
    'community.subtitle': 'Junte-se à família Pudgy Chicken. Um lugar onde a tecnologia encontra a agricultura, criando um futuro mais sustentável para todos!',
    'community.stats.farmers': 'Fazendeiros Ativos',
    'community.stats.farmers.desc': 'Uma comunidade global de agricultores digitais',
    'community.stats.messages': 'Mensagens',
    'community.stats.messages.desc': 'Conversas sobre agricultura de criadores caseiros e sustentável',
    'community.stats.events': 'Eventos',
    'community.stats.events.desc': 'Workshops e conferências sobre tokenização',
    'community.stats.sustainability': 'Sustentabilidade',
    'community.stats.sustainability.desc': 'Promovendo agricultura responsável',
    'community.innovate': 'Inove, Participe e Cultive',
    'community.description': 'A comunidade Pudgy Chickens é mais do que apenas holders de colecionáveis. Somos uma família global unidos pela sustentabilidade, inovação agrícola, educação e desenvolvimento de projetos utilizando a tecnologia blockchain.',
    'community.features.workshops': 'Acesso a educação sobre a tecnologia blockchain',
    'community.features.decisions': 'Participe de decisões da comunidade',
    'community.features.projects': 'Colabore em projetos sustentáveis',
    'community.features.connect': 'Conecte-se com criadores de agricultura caseira do mundo todo',
    'community.cta.twitter': 'Seguir no X',
    'community.media.title': 'Pudgy Media',
    'community.media.subtitle': 'Acompanhe as últimas novidades, inovações agrícolas e conteúdo exclusivo.',
    'community.media.view': 'Ver Pudgy Media',
    'community.media.tokenization': 'Novo sistema de tokenização!',
    'community.media.workshop': 'Curso avançado de RWA para seu negócio',
    'community.media.hoursAgo': 'Há 2 horas',
    'community.media.hoursAgo2': 'Há 5 horas',

    // PudgyEggs
    'eggcoin.badge': 'Ovos Digitais',
    'eggcoin.title': 'PudgyEggs',
    'eggcoin.subtitle': 'A primeira representação digital de ovos que pode ser trocada por ovos reais!',
    'eggcoin.feature1.title': 'Troca por Ovos',
    'eggcoin.feature1.desc': 'Seus PudgyEggs podem ser trocados por ovos frescos.',
    'eggcoin.feature2.title': 'Começando no ES',
    'eggcoin.feature2.desc': 'Inicialmente disponível para residentes do Espírito Santo, com expansão gradual.',
    'eggcoin.feature3.title': 'Ovos por Assinatura',
    'eggcoin.feature3.desc': 'Em breve: assinatura mensal com benefícios exclusivos para colecionadores.',
    'eggcoin.how.title': 'Como Funciona?',
    'eggcoin.phase1.title': '🌱 Fase Atual',
    'eggcoin.phase1.item1': '• Compra de PudgyEggs disponível',
    'eggcoin.phase1.item2': '• Troca por ovos no Espírito Santo',
    'eggcoin.phase1.item3': '• Benefícios para colecionadores NFT',
    'eggcoin.phase2.title': '🚀 Futuro',
    'eggcoin.phase2.item1': '• Expansão para outras regiões',
    'eggcoin.phase2.item2': '• Assinatura mensal de ovos',
    'eggcoin.phase2.item3': '• Benefícios exclusivos para holders',
    'eggcoin.cta.buy': 'Comprar PudgyEggs Agora',
    'eggcoin.modal.title': 'Comprar PudgyEggs',
    'eggcoin.modal.description': 'Custo em ETH e USDC conforme a quantidade. Cada token PudgyEggs poderá ser trocado por um ovo, conforme disponibilidade e local.',
    'eggcoin.modal.connectWallet': 'Conecte sua carteira para comprar PudgyEggs.',
    'eggcoin.modal.wrongNetwork': 'Conecte-se à rede Base Sepolia para comprar PudgyEggs.',
    'eggcoin.modal.switchNetwork': 'Mudar para Base Sepolia',
    'eggcoin.modal.disclaimer': 'Cada token PudgyEggs poderá ser trocado por um ovo real, dependendo da disponibilidade e do local. O benefício de ter PudgyEggs é a interação com o protocolo: holders e usuários terão benefícios das nossas farms e coleções.',
    'eggcoin.modal.amount': 'Quantidade de PudgyEggs',
    'eggcoin.modal.costLabel': 'Custo total (estimativa)',
    'eggcoin.modal.loadingPrice': 'Carregando preço...',
    'eggcoin.modal.payWith': 'Pagar com',
    'eggcoin.modal.approveUsdc': 'Aprovar USDC',
    'eggcoin.modal.approving': 'Aprovando...',
    'eggcoin.modal.minting': 'Mintando...',
    'eggcoin.modal.mintButton': 'Comprar PudgyEggs',
    'eggcoin.modal.approveSuccess': 'USDC aprovado. Agora clique em Comprar PudgyEggs.',
    'eggcoin.modal.success': 'PudgyEggs comprados com sucesso!',
    'eggcoin.modal.insufficientEth': 'Saldo ETH insuficiente.',
    'eggcoin.modal.insufficientUsdc': 'Saldo USDC insuficiente.',
    'eggcoin.modal.usdcNotAvailable': 'USDC não disponível nesta rede.',
    'uniqueCollectible.modal.title': 'Você foi contemplado com um colecionável único',
    'uniqueCollectible.modal.subtitle': 'Este NFT exclusivo faz parte da coleção especial PudgyFarms.',
    'uniqueCollectible.modal.attributes': 'Atributos',
    'uniqueCollectible.modal.viewOnChain': 'Ver na blockchain',
    'eligibility.whitelist.cta': 'Você está na whitelist! Resgate seu NFT de graça.',
    'eligibility.whitelist.goToMint': 'Ir para o Free Mint',
    
    // Footer
    'footer.description': 'Uma plataforma nascida na web3 que promove sustentabilidade, inovação agrícola e comunidade através da tokenização de galinhas.',
    'footer.collections': 'Coleções',
    'footer.shop': 'Loja',
    'footer.newsletter': 'Curso de Desenvolvimento',
    'footer.newsletter.subtitle': 'Inscreva-se para receber informações sobre o PudgyFarms, curso de desenvolvimento blockchain, novidades do projeto e benefícios exclusivos.',
    'footer.newsletter.email': 'Seu email',
    'footer.newsletter.subscribe': 'Inscrever-se',
    'footer.copyright': '© 2024 Pudgy Chickens. Todos os direitos reservados.',
    'footer.links.terms': 'Termos de Uso',
    'footer.links.privacy': 'Política de Privacidade',
    'footer.links.support': 'Suporte',
    'footer.omnes.description': 'Projeto educacional com smart contracts open-source para tokenização de galinhas reais.',
    'footer.omnes.educational': 'Curso completo de desenvolvimento de smart contracts disponível.',
    'footer.omnes.developedBy': 'Projeto Desenvolvido por',
    
    // Battle
    'battle.title': 'Arena de Batalha',
    'battle.subtitle': 'Escolha seus NFTs favoritos e participe de batalhas épicas na arena. Crie uma batalha ou participe de uma existente!',
    'battle.select': 'Selecione seu NFT',
    'battle.create': 'Criar Nova Batalha',
    'battle.your': 'Suas Batalhas',
    'battle.available': 'Batalhas Disponíveis',
    'battle.none': 'Nenhuma batalha disponível',
    'battle.none.subtitle': 'Seja o primeiro a criar uma batalha e aguarde outros jogadores entrarem!',
    'battle.select.nft': 'Selecione um NFT para criar uma batalha ou participar de uma existente.',
    'battle.join': 'Entrar na Batalha',
    'battle.enter': 'Entrar na Arena',
    'battle.active': 'Batalha em andamento...',
    'battle.finished': 'Batalha Finalizada',
    'battle.winner': 'Vencedor',
    'battle.attack': 'Ataque',
    'battle.speed': 'Velocidade',
    'battle.players': 'Jogadores',
    'battle.waiting': 'Aguardando',
    'battle.your.battle': 'Sua Batalha',
    'battle.battling': 'BATALHANDO',
    'battle.victory': 'VITÓRIA!',
    'battle.winner.is': 'é o vencedor!',
    'battle.congratulations': 'Parabéns pela vitória épica!',
    'battle.select.player1': 'Selecione um NFT para o Jogador 1',
    'battle.select.player2': 'Selecione um NFT para o Jogador 2',
    'battle.waiting.opponent': 'Aguardando oponente entrar na batalha...',
    'battle.start': 'Iniciar Batalha',
    'battle.leave': 'Sair da Batalha',
    'battle.betting.title': 'Contribuir com PudgyEggs',
    'battle.betting.description': 'Contribua com PudgyEggs para aumentar as recompensas da batalha. O vencedor recebe os PudgyEggs contribuídos!',
    'battle.betting.preset': 'Valores Sugeridos',
    'battle.betting.custom': 'Valor Personalizado',
    'battle.betting.current': 'Contribuição Atual',
    'battle.betting.reward': 'Recompensa',
    'battle.betting.maxWarning': 'Máximo permitido: {max} PudgyEggs',
    'battle.betting.pot': 'Total Contribuído',
    'battle.betting.creator': 'Criador',
    'battle.betting.participant': 'Participante',
    'battle.betting.arena.title': 'PudgyEggs da Batalha',
    'battle.betting.arena.pot': 'Total contribuído',
    'battle.betting.arena.winner': 'O vencedor recebe todos os PudgyEggs contribuídos!',
    'battle.betting.rewards': 'Recompensas PudgyEggs',
    'battle.betting.rewards.description': 'Você recebeu todos os PudgyEggs contribuídos!',
    'battle.howItWorks.button': 'Entenda como funciona',
    'battle.howItWorks.title': 'Como Funciona o Sistema de Batalhas',
    'battle.howItWorks.rarity.title': 'Raridade dos NFTs',
    'battle.howItWorks.rarity.description': 'Cada NFT tem sua raridade conforme o ID. O mais raro é o ID 1 e o menos raro é o ID 10. Quanto mais raro, maiores são os valores das skills que foram definidas no mint de forma totalmente aleatória.',
    'battle.howItWorks.skills.title': 'Skills dos NFTs',
    'battle.howItWorks.skills.description': 'As skills são: power, speed, health, clucking e broodPower. É impossível ter todas como 10, garantindo um sistema justo de batalhas.',
    'battle.howItWorks.vrf.title': 'Sistema VRF da Chainlink',
    'battle.howItWorks.vrf.description': 'Na batalha usamos VRF da Chainlink que garante que não há como burlar a aleatoriedade da skill escolhida na batalha.',
    'battle.howItWorks.gameplay.title': 'Como Jogar',
    'battle.howItWorks.gameplay.description': 'Pense como Super Trunfo! Será escolhido aleatoriamente uma skill e quem tiver a maior irá vencer e levar o colecionável do outro, além de ganhar uma pontuação de vitórias atrelada ao seu colecionável. Isso pode fazer seu Pudgy Chicken ser mais raro e valer mais no mercado secundário.',
    'battle.howItWorks.tip.title': '💡 Dica Importante',
    'battle.howItWorks.tip.description': 'Os IDs de 10 ao 5, mesmo sendo menos raros, ainda têm chances de ganhar. Mas se você tem um ID 10 e tenta batalhar com um super raro de ID 1, a possibilidade de vitória é improvável. Boa diversão!',
    
    // Farm
    'farm.title': 'Fazenda Digital',
    'farm.subtitle': 'Gerencie sua fazenda digital e tokenize seus animais',
    'farm.create': 'Criar Fazenda',
    'farm.tokenize': 'Tokenizar Animais',
    'farm.animals': 'Animais',
    'farm.tokens': 'Tokens',
    'farm.earnings': 'Ganhos',
    'farm.level': 'Nível',
    'farm.experience': 'Experiência',
    'farm.energy': 'Energia',
    'farm.food': 'Comida',
    'farm.water': 'Água',
    'farm.health': 'Saúde',
    'farm.happiness': 'Felicidade',
    'farm.breeding': 'Reprodução',
    'farm.market': 'Mercado',
    'farm.leaderboard': 'Ranking',
    'farm.achievements': 'Conquistas',
    'farm.settings': 'Configurações',
    'farm.help': 'Ajuda',
    'farm.tutorial': 'Tutorial',
    'farm.guide': 'Guia',
    'farm.faq': 'FAQ',
    'farm.support': 'Suporte',
    'farm.contact': 'Contato',
    'farm.about': 'Sobre',
    'farm.terms': 'Termos',
    'farm.privacy': 'Privacidade',
    'farm.cookies': 'Cookies',
    'farm.language': 'Idioma',
    'farm.theme': 'Tema',
    'farm.sound': 'Som',
    'farm.music': 'Música',
    'farm.effects': 'Efeitos',
    'farm.notifications': 'Notificações',
    'farm.email': 'Email',
    'farm.push': 'Push',
    'farm.sms': 'SMS',
    'farm.social': 'Social',
    'farm.share': 'Compartilhar',
    'farm.invite': 'Convidar',
    'farm.referral': 'Indicação',
    'farm.rewards': 'Recompensas',
    'farm.bonus': 'Bônus',
    'farm.daily': 'Diário',
    'farm.weekly': 'Semanal',
    'farm.monthly': 'Mensal',
    'farm.special': 'Especial',
    'farm.event': 'Evento',
    'farm.season': 'Temporada',
    'farm.holiday': 'Feriado',
    'farm.anniversary': 'Aniversário',
    'farm.birthday': 'Aniversário',
    'farm.celebration': 'Celebração',
    'farm.party': 'Festa',
    'farm.festival': 'Festival',
    'farm.carnival': 'Carnaval',
    'farm.parade': 'Desfile',
    'farm.contest': 'Concurso',
    'farm.competition': 'Competição',
    'farm.tournament': 'Torneio',
    'farm.championship': 'Campeonato',
    'farm.league': 'Liga',
    'farm.division': 'Divisão',
    'farm.rank': 'Classificação',
    'farm.score': 'Pontuação',
    'farm.points': 'Pontos',
    'farm.coins': 'Tokens',
    'farm.gems': 'Gemas',
    'farm.crystals': 'Cristais',
    'farm.diamonds': 'Diamantes',
    'farm.gold': 'Ouro',
    'farm.silver': 'Prata',
    'farm.bronze': 'Bronze',
    'farm.platinum': 'Platina',
    'farm.titanium': 'Titânio',
    'farm.steel': 'Aço',
    'farm.iron': 'Ferro',
    'farm.copper': 'Cobre',
    'farm.aluminum': 'Alumínio',
    'farm.zinc': 'Zinco',
    'farm.nickel': 'Níquel',
    'farm.tin': 'Estanho',
    'farm.lead': 'Chumbo',
    'farm.mercury': 'Mercúrio',
    'farm.arsenic': 'Arsênio',
    'farm.antimony': 'Antimônio',
    'farm.bismuth': 'Bismuto',
    'farm.polonium': 'Polônio',
    'farm.astatine': 'Astato',
    'farm.radon': 'Radônio',
    'farm.francium': 'Frâncio',
    'farm.radium': 'Rádio',
    'farm.actinium': 'Actínio',
    'farm.thorium': 'Tório',
    'farm.protactinium': 'Protactínio',
    'farm.uranium': 'Urânio',
    'farm.neptunium': 'Netúnio',
    'farm.plutonium': 'Plutônio',
    'farm.americium': 'Amerício',
    'farm.curium': 'Cúrio',
    'farm.berkelium': 'Berquélio',
    'farm.californium': 'Califórnio',
    'farm.einsteinium': 'Einstênio',
    'farm.fermium': 'Férmio',
    'farm.mendelevium': 'Mendelévio',
    'farm.nobelium': 'Nobélio',
    'farm.lawrencium': 'Laurêncio',
    'farm.rutherfordium': 'Rutherfórdio',
    'farm.dubnium': 'Dúbnio',
    'farm.seaborgium': 'Seabórgio',
    'farm.bohrium': 'Bóhrio',
    'farm.hassium': 'Hássio',
    'farm.meitnerium': 'Meitnério',
    'farm.darmstadtium': 'Darmstádio',
    'farm.roentgenium': 'Roentgênio',
    'farm.copernicium': 'Copernício',
    'farm.nihonium': 'Nihônio',
    'farm.flerovium': 'Fleróvio',
    'farm.moscovium': 'Moscóvio',
    'farm.livermorium': 'Livermório',
    'farm.tennessine': 'Tenesso',
    'farm.oganesson': 'Oganessônio',
    
    // Farm Collection
    'farm.collection.title': 'Tokenizar Seus Animais',
    'farm.collection.subtitle': 'Transforme seus animais em NFTs únicos! Crie coleções de RWAnimals (Real World Animals) e contribua para a revolução da agricultura digital. Comece sua jornada como as Pudgy Chickens!',
    'farm.collection.info.title': 'Informações dos RWAnimals',
    'farm.collection.name.label': 'Nome da Coleção RWAnimals *',
    'farm.collection.name.placeholder': 'Ex: Galinhas Douradas da Fazenda São José',
    'farm.collection.description.label': 'Descrição *',
    'farm.collection.description.placeholder': 'Descreva seus RWAnimals, suas características únicas, raça, origem e o que os torna especiais para a agricultura...',
    'farm.collection.image.label': 'Link das Imagens dos RWAnimals *',
    'farm.collection.image.placeholder': 'https://exemplo.com/imagens-animais',
    'farm.collection.image.help': 'Forneça um link para as imagens dos seus animais (IPFS, Google Drive, etc.)',
    'farm.collection.region.label': 'Região *',
    'farm.collection.region.placeholder': 'Selecione a região da sua fazenda',
    'farm.collection.type.label': 'Tipo de Fazenda *',
    'farm.collection.type.placeholder': 'Selecione o tipo da sua fazenda',
    'farm.collection.supply.label': 'Total de NFTs',
    'farm.collection.supply.help': 'Número máximo de RWAnimals que podem ser tokenizados nesta coleção',
    'farm.collection.submit': 'Tokenizar RWAnimals',
    'farm.collection.submitting': 'Tokenizando RWAnimals...',
    'farm.collection.owner.title': 'Informações do Proprietário',
    'farm.collection.owner.email': 'Email',
    'farm.collection.owner.email.placeholder': 'seu@email.com',
    'farm.collection.owner.name': 'Nome do Proprietário',
    'farm.collection.owner.name.placeholder': 'Seu nome completo',
    'farm.collection.owner.farm': 'Nome da Fazenda',
    'farm.collection.owner.farm.placeholder': 'Nome da sua fazenda',
    'farm.collection.preview.title': 'Preview dos RWAnimals',
    'farm.collection.preview.name': 'Nome dos RWAnimals',
    'farm.collection.preview.description': 'Descrição dos seus animais aparecerá aqui...',
    'farm.collection.preview.steps.title': 'Próximos passos:',
    'farm.collection.preview.steps.description': 'Após tokenizar seus RWAnimals, você poderá fazer upload das imagens individuais e definir os metadados de cada animal NFT.',
    'farm.collection.success.title': 'Coleção criada com sucesso!',
    'farm.collection.success.description': 'Sua coleção foi criada e está sendo processada.',
    
    // Farm Types
    'farm.type.poultry': 'Avicultura',
    'farm.type.cattle': 'Pecuária',
    'farm.type.agriculture': 'Agricultura',
    'farm.type.aquaculture': 'Aquicultura',
    'farm.type.mixed': 'Mista',
    
    // Regions
    'farm.region.north': 'Norte',
    'farm.region.northeast': 'Nordeste',
    'farm.region.centerwest': 'Centro-Oeste',
    'farm.region.southeast': 'Sudeste',
    'farm.region.south': 'Sul',
    
    // Wallet
    'wallet.connected': 'Conectado',
    'wallet.network': 'Rede',
    'wallet.balance': 'Saldo',
    'wallet.manage': 'Gerenciar',
    'wallet.explorer': 'Explorer',
    'wallet.disconnect': 'Desconectar',
    'wallet.copy': 'Copiar',
    'wallet.copied': 'Copiado!',
    'wallet.switch': 'Trocar Carteira',
    'wallet.unsupported': 'Rede não suportada',
    'wallet.error': 'Erro na carteira',
    'wallet.connecting': 'Conectando...',
    'wallet.reconnecting': 'Reconectando...',
    
    // Whitelist
    'whitelist.title': 'Solicitar Acesso à Whitelist',
    'whitelist.description': 'VAGAS LIMITADAS! Preencha o formulário abaixo para garantir sua vaga na whitelist do Pudgy Chickens.',
    'whitelist.connectWalletFirst': 'Conecte sua carteira primeiro',
    'whitelist.nameRequired': 'Nome é obrigatório',
    'whitelist.submittedSuccessfully': 'Solicitação enviada com sucesso!',
    'whitelist.submissionError': 'Erro ao enviar solicitação',
    'whitelist.checkingStatus': 'Verificando status...',
    'whitelist.statusTitle': 'Status da Solicitação',
    'whitelist.walletAddress': 'Endereço da Carteira',
    'whitelist.name': 'Nome',
    'whitelist.email': 'Email',
    'whitelist.twitterPost': 'Link do Post no Twitter',
    'whitelist.instagramPost': 'Link do Post no Instagram',
    'whitelist.linkedinPost': 'Link do Post no LinkedIn',
    'whitelist.otherSocial': 'Outra Rede Social',
    'whitelist.submittedAt': 'Enviado em',
    'whitelist.notes': 'Observações',
    'whitelist.pendingMessage': 'Sua solicitação está sendo analisada. Você será notificado quando houver uma atualização.',
    'whitelist.namePlaceholder': 'Seu nome completo (opcional)',
    'whitelist.emailPlaceholder': 'seu@email.com (opcional)',
    'whitelist.emailOptional': 'Email opcional - usado apenas para benefícios e informações do ecossistema',
    'whitelist.twitterPostPlaceholder': 'https://twitter.com/usuario/status/...',
    'whitelist.instagramPostPlaceholder': 'https://instagram.com/p/...',
    'whitelist.linkedinPostPlaceholder': 'https://linkedin.com/posts/...',
    'whitelist.otherSocialPlaceholder': 'https://...',
    'whitelist.submit': 'Enviar Solicitação',
    'whitelist.submitting': 'Enviando...',
    'whitelist.approved': 'Aprovado',
    'whitelist.rejected': 'Rejeitado',
    'whitelist.pending': 'Pendente',
    'whitelist.unknown': 'Desconhecido',
    'whitelist.benefits.title': 'Mint Gratuito + Curso Educacional',
    'whitelist.benefits.description': 'Mint gratuito da sua galinha NFT real, desconto especial no curso completo de desenvolvimento dos smart contracts e desconto em produtos educacionais da Omnes.',
    'whitelist.process.title': 'Projeto Real + Open Source',
    'whitelist.process.description': 'Cada NFT representa uma galinha física em nosso galinheiro. Smart contracts totalmente open-source para aprendizado e desenvolvimento educacional.',
    'whitelist.community.title': 'Comunidade Premium',
    'whitelist.community.description': 'Faça parte de uma comunidade selecionada com acesso antecipado a novos recursos e eventos exclusivos.',
    'whitelist.backToHome': 'Voltar ao Início',
    'whitelist.whyJoin.title': 'Por que se juntar à Whitelist?',
    'whitelist.whyJoin.subtitle': 'VAGAS LIMITADAS! Descubra os benefícios exclusivos de fazer parte da nossa comunidade premium.',
    'whitelist.suggestedMessage.title': 'Mensagem Sugerida para Compartilhar',
    'whitelist.suggestedMessage.text': 'Use esta mensagem ao compartilhar o projeto nas suas redes sociais:',
    'whitelist.suggestedMessage.example': 'Vou participar da primeira tokenização de galinhas REAIS do mundo! 🐔 Cada NFT representa uma galinha física em nosso galinheiro. Projeto educacional com smart contracts open-source da Omnes. Vagas LIMITADAS para free mint! Veja nosso galinheiro: https://youtube.com/watch?v=HHwmYjLl8S8 🚀 #PudgyFarms #RealWorldAnimals #Tokenização #Omnes #OpenSource',
    'whitelist.lgpd.consent': 'Concordo com o tratamento dos meus dados pessoais conforme a LGPD. Os dados serão utilizados estritamente para benefícios e envio de informações sobre cursos e produtos do ecossistema Pudgy Chickens.',
    'whitelist.limitedSpots.title': 'VAGAS LIMITADAS',
    'whitelist.limitedSpots.description': 'Vagas limitadas para mint gratuito. Garante já sua vaga!',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.close': 'Fechar',
    'common.save': 'Salvar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.more': 'Ver mais',
    'common.less': 'Ver menos',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.collection': 'Collection',
    'nav.shop': 'Shop',
    'nav.battle': 'Battle',
    'nav.farm': 'Farm',
    'nav.whitelist': 'Mint',
    'nav.community': 'Community',
    'nav.connect': 'Connect Wallet',
    
    // Hero
    'hero.title': 'Pudgy Farms',
    'hero.subtitle': 'We started with the Pudgy Chickens collection - the world\'s first REAL chicken tokenization! Each collectible can be exchanged for a real physical chicken, depending on availability and region. Fully open-source project.',
    'hero.info.title': 'About Collectibles',
    'hero.info.description': 'Pudgy Chickens are digital collectibles that represent real products (chickens or eggs). This is a collectible product, not a financial investment. Each collectible can be exchanged for a real physical chicken, subject to availability and region. Eggs can also be exchanged for real eggs when available.',
    'hero.info.disclaimer': '⚠️ Important: This is a collectible product, not an investment. The asset represents a physical product (chicken or eggs) and can be exchanged depending on availability and region.',
    'hero.cta.primary': 'Tokenize your RWAnimal',
    'hero.cta.secondary': 'View Our Farm',
    'hero.cta.learnMore': 'Discover More',
    'hero.cta.mint': 'Mint your PudgyChicken',
    'hero.cta.contact': 'Contact Us',
    'hero.stats.chickens': 'Pudgy Chickens Collection',
    'hero.stats.tokenized': 'Real Tokenization',
    'hero.stats.farms': 'Educational Project',
    'hero.education.disclaimer': '⚠️ Important: This is a fully collaborative project with no financial return expectation. All participants will have benefits in everything developed and produced in the ecosystem farms.',
    'hero.education.title': 'Collaborative & Educational Project',
    'hero.education.subtitle': 'Complete Smart Contracts Course',
    'hero.education.description': 'This is a collaborative and educational project that includes a complete course on the RWA (Real World Assets) smart contracts developed for this platform. When we reach 1,800 mints, the course will be made completely free on YouTube for everyone! Additionally, part of the value will be allocated to projects developed by students, community, and ecosystem farms.',
    'hero.education.goal': 'Goal: 1,800 Mints',
    'hero.education.benefits': 'Collaborative Benefits',
    'hero.education.benefits.list': '• Free course on YouTube\n• Part of value for community projects\n• Benefits in all ecosystem farms\n• Participation in developed projects\n• Collaborative developer community',
    
    // Detailed Description
    'hero.detailed.description': 'PudgyFarm represents a complete revolution in the Brazilian Web3 ecosystem, combining real asset tokenization, educational gamification and sustainable agricultural development. Holders will have exclusive benefits in all future PudgyFarm tokenizations, including real products and animals and their inputs, with the only restriction being regional availability. Our platform is fully interactive, allowing battles between collectibles where you can win even with less rare assets, based on victory history and ecosystem interaction. The more active and engaged you are, the higher your reputation will be, providing even more benefits and chances of victory. In addition to battles, you can contribute with PudgyEggs, digital representation of real eggs from chickens. PudgyFarm offers its own tokenization system, allowing anyone to digitize their real animals without technical blockchain knowledge, participating in the entire ecosystem and its benefits. It\'s a complete ecosystem: real asset tokenization, collectibles with unique rarities and abilities, reputation system, fair battles and digital representation of real eggs from chickens. All of this supported by an educational course with the goal of training more developers and boosting the growth of the Web3 ecosystem in Brazil. Join the whitelist and be part of this "Web3 Animals Revolution" focused on economic and educational growth.',
    
    // Details Page
    'details.backToHome': 'Back to Home',
    'details.title': 'Web3 Animals Revolution',
    'details.subtitle': 'Discover how PudgyFarm is transforming Brazilian agribusiness through blockchain technology and real asset tokenization.',
    'details.features.title': 'Main Features',
    'details.features.subtitle': 'A complete ecosystem that combines technology, education and sustainability',
    'details.features.realAssets.title': 'Real Asset Tokenization',
    'details.features.realAssets.description': 'Each NFT will represent a real animal in our ecosystem, connecting the digital world to the physical.',
    'details.features.community.title': 'Premium Community',
    'details.features.community.description': 'Exclusive access to benefits, real products and participation in community decisions.',
    'details.features.battles.title': 'Battle System',
    'details.features.battles.description': 'Battle with other collectibles in a fair system based on reputation and strategy.',
    'details.features.eggcoin.title': 'PudgyEggs - Real Eggs',
    'details.features.eggcoin.description': 'Digital representation of real eggs from chickens. Each PudgyEgg can be exchanged for fresh eggs from ecosystem farms, depending on availability and region.',
    'details.features.reputation.title': 'Reputation System',
    'details.features.reputation.description': 'The more active and engaged you are, the higher your reputation and chances of victory in battles.',
    'details.features.education.title': 'Educational Training',
    'details.features.education.description': 'Complete course on the developed smart contracts. When we reach 1,800 mints, the course will be completely free for all holders!',
    'details.education.title': 'Collaborative & Educational Project: Smart Contracts Course',
    'details.education.subtitle': 'Learn with the real contracts developed for the project',
    'details.education.description': 'This is a collaborative and educational project aimed at training Web3 developers in Brazil. We include a complete course on the smart contracts developed specifically for Pudgy Farms, covering from basic concepts to advanced implementations. The course will be made completely free on YouTube.',
    'details.education.goal.title': 'Goal: 1,800 Mints = Free Course',
    'details.education.goal.description': 'When we reach 1,800 mints of collectibles, the complete course will be made completely free on YouTube for everyone!',
    'details.education.funds.title': 'After 1,800 Mints: Community Investment',
    'details.education.funds.description': 'When we pass 1,800 mints, part of the value will be allocated to:',
    'details.education.collaborative.title': 'Fully Collaborative Project',
    'details.education.collaborative.description': 'This is a fully collaborative project with no financial return expectation. All participants will have benefits in everything developed and produced in the ecosystem farms. The focus is on education, community development, and sustainable growth of the Brazilian Web3 ecosystem.',
    'details.education.funds.description': 'When we pass 1,800 mints, part of the value will be allocated to:',
    'details.education.funds.list': '• Projects developed by course students\n• Community initiatives\n• Development and maintenance of ecosystem farms\n• New educational content\n• Expansion of the collaborative project',
    'details.education.goal.current': 'Current Mints',
    'details.education.goal.target': 'Goal',
    'details.education.benefits.title': 'Benefits for Holders and Players',
    'details.education.benefits.holders': 'For Holders:',
    'details.education.benefits.holders.list': '• Free complete smart contracts course\n• Exclusive access to new educational content\n• Priority in future tokenizations\n• Premium developer community\n• Priority technical support',
    'details.education.benefits.players': 'For Battle Game Players:',
    'details.education.benefits.players.list': '• Special rewards in battles\n• Exclusive NFTs for participation\n• Premium ranking with benefits\n• Early access to new features\n• Tournaments with educational prizes',
    'details.education.cta': 'Participate and Help Reach the Goal!',
    'details.ecosystem.title': 'Our Ecosystem',
    'details.ecosystem.tokenization.title': 'Simplified Tokenization',
    'details.ecosystem.tokenization.description': 'Proprietary system that allows digitizing real animals without technical blockchain knowledge.',
    'details.ecosystem.education.title': 'Web3 Education',
    'details.ecosystem.education.description': 'Educational course focused on training developers and boosting the growth of the Web3 ecosystem in Brazil.',
    'details.cta.title': 'Join the Revolution',
    'details.cta.description': 'Join the world\'s first real animal tokenization platform and be part of the future of agribusiness.',
    'details.cta.mint': 'Mint your PudgyChicken',
    'details.cta.explore': 'Explore Project',
    
    // Creator Section
    'details.creator.title': 'About the Creator',
    'details.creator.subtitle': 'Meet the story behind the first tokenized chicken coop',
    'details.creator.name': 'Afonso Dalvi',
    'details.creator.role': 'Creator of the First Tokenized Chicken Coop',
    'details.creator.experience': '7+ years of technology experience',
    'details.creator.description': 'Afonso is the creator of Pudgy Farm, since childhood he has always loved animals and when he grew up he fell in love with technology. With more than 7 years of experience in the field, he decided to combine these two passions with the goal of helping global agribusiness and Web3 growth through an open-source project and educational course development.',
    'details.creator.childhood': 'Childhood',
    'details.creator.today': 'Today',
    
    // Vision Section
    'details.vision.title': 'Our Vision',
    'details.vision.ecosystem.title': 'Complete Ecosystem',
    'details.vision.ecosystem.description': 'PudgyFarm represents a complete revolution in the Brazilian Web3 ecosystem, transforming education and agribusiness through real assets, with asset gamification and educational and agricultural development.',
    'details.vision.benefits.title': 'Exclusive Benefits',
    'details.vision.benefits.description': 'Holders will have exclusive benefits in all future PudgyFarm tokenizations, including real products and animals and their inputs, with the only restriction being regional availability. Our platform is fully interactive, allowing battles between collectibles where you can win even with less rare assets.',
    'details.vision.conclusion.title': 'Web3 Animals Revolution',
    'details.vision.conclusion.description': 'It\'s a complete ecosystem: real asset tokenization, collectibles with unique rarities and abilities, reputation system, fair battles and digital representation of eggs pegged to real value. All of this supported by an educational course with the goal of training more developers and boosting the growth of the Web3 ecosystem in Brazil. The collections are not investments but digital representations with real utilities.',
    
    // Animated Section
    'gifs.title': 'Collection GIFs',
    'gifs.subtitle': 'Download and share animated GIFs',
    
    // Collection
    'collection.title': 'Our Collections',
    'collection.subtitle': 'Welcome to the world of Pudgy Chickens, a web3-born platform that promotes sustainability, agricultural innovation and community through chicken tokenization.',
    'collection.explore': 'Explore All Collections',
    'collection.items': 'items',
    'collection.floor': 'Floor Price',
    'collection.view': 'View Collection',
    'collection.original': 'The original collection of 10,000 unique chickens tokenized on the blockchain.',
    'collection.lil': '5,000 premium lineage chicks. Small but promising.',
    'myNFTs.title': 'My NFTs',
    'myNFTs.subtitle': 'All your Pudgy Chickens in one place — standard collection and special collectibles.',
    'myNFTs.special': 'Special',
    'myNFTs.collection': 'Pudgy Chickens',
    'myNFTs.viewOnChain': 'View on blockchain',
    'myNFTs.empty.title': 'No NFTs yet',
    'myNFTs.empty.description': 'Connect your wallet and mint on the whitelist page to start your collection.',
    'myNFTs.empty.cta': 'Go to Mint',
    'myNFTs.rarity.common': 'Common',
    'myNFTs.rarity.rare': 'Rare',
    'myNFTs.rarity.epic': 'Epic',
    'myNFTs.rarity.legendary': 'Legendary',
    
    // Shop
    'shop.title': 'Asset Shop',
    'shop.subtitle': 'Collect unique tokenized chickens. Each asset is unique and has special rarity and characteristics. Start your collection today!',
    'shop.buy': 'Buy',
    'shop.viewAll': 'View All Assets',
    'shop.reviews': 'reviews',
    'shop.reputation': 'Reputation',
    
    // Community
    'community.title': 'The Community',
    'community.subtitle': 'Join the Pudgy Chickens family. A place where technology meets agriculture, creating a more sustainable future for everyone!',
    'community.stats.farmers': 'Active Farmers',
    'community.stats.farmers.desc': 'A global community of digital farmers',
    'community.stats.messages': 'Messages',
    'community.stats.messages.desc': 'Conversations about home-based and sustainable agriculture',
    'community.stats.events': 'Events',
    'community.stats.events.desc': 'Workshops and conferences on tokenization',
    'community.stats.sustainability': 'Sustainability',
    'community.stats.sustainability.desc': 'Promoting responsible agriculture',
    'community.innovate': 'Innovate, Participate and Cultivate',
    'community.description': 'The Pudgy Chickens community is more than just collectible holders. We are a global family united by sustainability, agricultural innovation, education and development of projects using blockchain technology.',
    'community.features.workshops': 'Access to blockchain technology education',
    'community.features.decisions': 'Participate in community decisions',
    'community.features.projects': 'Collaborate on sustainable projects',
    'community.features.connect': 'Connect with home-based agriculture creators from around the world',
    'community.cta.twitter': 'Follow on X',
    'community.media.title': 'Pudgy Media',
    'community.media.subtitle': 'Follow the latest news, agricultural innovations and exclusive content.',
    'community.media.view': 'View Pudgy Media',
    'community.media.tokenization': 'New tokenization system!',
    'community.media.workshop': 'Advanced RWA course for your business',
    'community.media.hoursAgo': '2 hours ago',
    'community.media.hoursAgo2': '5 hours ago',

    // PudgyEggs
    'eggcoin.badge': 'Real Eggs from Chickens',
    'eggcoin.title': 'PudgyEggs',
    'eggcoin.subtitle': 'Digital representation of real eggs from your chickens!',
    'eggcoin.feature1.title': 'Exchange for Real Eggs',
    'eggcoin.feature1.desc': 'Your PudgyEggs can be exchanged for fresh eggs from ecosystem farms.',
    'eggcoin.feature2.title': 'Starting in ES',
    'eggcoin.feature2.desc': 'Initially available for Espírito Santo residents, with gradual expansion.',
    'eggcoin.feature3.title': 'Eggs by Subscription',
    'eggcoin.feature3.desc': 'Coming soon: monthly subscription with exclusive benefits for collectors.',
    'eggcoin.how.title': 'How It Works?',
    'eggcoin.phase1.title': '🌱 Current Phase',
    'eggcoin.phase1.item1': '• PudgyEggs acquisition available',
    'eggcoin.phase1.item2': '• Exchange for real eggs in Espírito Santo',
    'eggcoin.phase1.item3': '• Benefits for NFT collectors',
    'eggcoin.phase2.title': '🚀 Future',
    'eggcoin.phase2.item1': '• Expansion to other regions',
    'eggcoin.phase2.item2': '• Monthly real egg subscription',
    'eggcoin.phase2.item3': '• Exclusive benefits for holders',
    'eggcoin.cta.buy': 'Get PudgyEggs Now',
    'eggcoin.modal.title': 'Buy PudgyEggs',
    'eggcoin.modal.description': 'Cost in ETH and USDC depends on amount. Each PudgyEggs token can be exchanged for one egg, subject to availability and location.',
    'eggcoin.modal.connectWallet': 'Connect your wallet to buy PudgyEggs.',
    'eggcoin.modal.wrongNetwork': 'Connect to Base Sepolia network to buy PudgyEggs.',
    'eggcoin.modal.switchNetwork': 'Switch to Base Sepolia',
    'eggcoin.modal.disclaimer': 'Each PudgyEggs token can be exchanged for one real egg, depending on availability and location. The benefit of holding PudgyEggs is interaction with the protocol: holders and users will have benefits from our farms and collections.',
    'eggcoin.modal.amount': 'Amount of PudgyEggs',
    'eggcoin.modal.costLabel': 'Total cost (estimate)',
    'eggcoin.modal.loadingPrice': 'Loading price...',
    'eggcoin.modal.payWith': 'Pay with',
    'eggcoin.modal.approveUsdc': 'Approve USDC',
    'eggcoin.modal.approving': 'Approving...',
    'eggcoin.modal.minting': 'Minting...',
    'eggcoin.modal.mintButton': 'Buy PudgyEggs',
    'eggcoin.modal.approveSuccess': 'USDC approved. You can now click Buy PudgyEggs.',
    'eggcoin.modal.success': 'PudgyEggs purchased successfully!',
    'eggcoin.modal.insufficientEth': 'Insufficient ETH balance.',
    'eggcoin.modal.insufficientUsdc': 'Insufficient USDC balance.',
    'eggcoin.modal.usdcNotAvailable': 'USDC not available on this network.',
    'uniqueCollectible.modal.title': 'You were granted a unique collectible',
    'uniqueCollectible.modal.subtitle': 'This exclusive NFT is part of the special PudgyFarms collection.',
    'uniqueCollectible.modal.attributes': 'Attributes',
    'uniqueCollectible.modal.viewOnChain': 'View on blockchain',
    'eligibility.whitelist.cta': "You're on the whitelist! Claim your free NFT.",
    'eligibility.whitelist.goToMint': 'Go to Free Mint',
    
    // Footer
    'footer.description': 'A web3-born platform that promotes sustainability, agricultural innovation and community through chicken tokenization.',
    'footer.collections': 'Collections',
    'footer.shop': 'Shop',
    'footer.newsletter': 'Development Course',
    'footer.newsletter.subtitle': 'Subscribe to receive information about PudgyFarms, blockchain development course, project updates and exclusive benefits.',
    'footer.newsletter.email': 'Your email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.copyright': '© 2024 Pudgy Chickens. All rights reserved.',
    'footer.links.terms': 'Terms of Use',
    'footer.links.privacy': 'Privacy Policy',
    'footer.links.support': 'Support',
    'footer.omnes.description': 'Educational project with open-source smart contracts for real chicken tokenization.',
    'footer.omnes.educational': 'Complete smart contract development course available.',
    'footer.omnes.developedBy': 'Project Developed by',
    
    // Battle
    'battle.title': 'Battle Arena',
    'battle.subtitle': 'Choose your favorite NFTs and participate in epic battles in the arena. Create a battle or join an existing one!',
    'battle.select': 'Select your NFT',
    'battle.create': 'Create New Battle',
    'battle.your': 'Your Battles',
    'battle.available': 'Available Battles',
    'battle.none': 'No battles available',
    'battle.none.subtitle': 'Be the first to create a battle and wait for other players to join!',
    'battle.select.nft': 'Select an NFT to create a battle or join an existing one.',
    'battle.join': 'Join Battle',
    'battle.enter': 'Enter Arena',
    'battle.active': 'Battle in progress...',
    'battle.finished': 'Battle Finished',
    'battle.winner': 'Winner',
    'battle.attack': 'Attack',
    'battle.speed': 'Speed',
    'battle.players': 'Players',
    'battle.waiting': 'Waiting',
    'battle.your.battle': 'Your Battle',
    'battle.battling': 'BATTLING',
    'battle.victory': 'VICTORY!',
    'battle.winner.is': 'is the winner!',
    'battle.congratulations': 'Congratulations on the epic victory!',
    'battle.select.player1': 'Select an NFT for Player 1',
    'battle.select.player2': 'Select an NFT for Player 2',
    'battle.waiting.opponent': 'Waiting for opponent to join the battle...',
    'battle.start': 'Start Battle',
    'battle.leave': 'Leave Battle',
    'battle.betting.title': 'Contribute with PudgyEggs',
    'battle.betting.description': 'Contribute with PudgyEggs to increase battle rewards. The winner receives the contributed PudgyEggs!',
    'battle.betting.preset': 'Suggested Amounts',
    'battle.betting.custom': 'Custom Amount',
    'battle.betting.current': 'Current Contribution',
    'battle.betting.reward': 'Reward',
    'battle.betting.maxWarning': 'Maximum allowed: {max} PudgyEggs',
    'battle.betting.pot': 'Total Contributed',
    'battle.betting.creator': 'Creator',
    'battle.betting.participant': 'Participant',
    'battle.betting.arena.title': 'Battle PudgyEggs',
    'battle.betting.arena.pot': 'Total contributed',
    'battle.betting.arena.winner': 'The winner receives all contributed PudgyEggs!',
    'battle.betting.rewards': 'PudgyEggs Rewards',
    'battle.betting.rewards.description': 'You received all contributed PudgyEggs!',
    'battle.howItWorks.button': 'Learn How It Works',
    'battle.howItWorks.title': 'How the Battle System Works',
    'battle.howItWorks.rarity.title': 'NFT Rarity',
    'battle.howItWorks.rarity.description': 'Each NFT has its rarity according to the ID. The rarest is ID 1 and the least rare is ID 10. The rarer the NFT, the higher the values of the skills that were defined at mint in a completely random way.',
    'battle.howItWorks.skills.title': 'NFT Skills',
    'battle.howItWorks.skills.description': 'The skills are: power, speed, health, clucking and broodPower. It is impossible to have all of them as 10, ensuring a fair battle system.',
    'battle.howItWorks.vrf.title': 'Chainlink VRF System',
    'battle.howItWorks.vrf.description': 'In battle we use Chainlink VRF which guarantees that there is no way to bypass the randomness of the skill chosen in battle.',
    'battle.howItWorks.gameplay.title': 'How to Play',
    'battle.howItWorks.gameplay.description': 'Think of it like Top Trumps! A skill will be randomly chosen and whoever has the highest will win and take the other\'s collectible, plus earn a victory score attached to your collectible. This can make your Pudgy Chicken rarer and worth more on the secondary market.',
    'battle.howItWorks.tip.title': '💡 Important Tip',
    'battle.howItWorks.tip.description': 'IDs from 10 to 5, even though they are less rare, still have chances of winning. But if you have an ID 10 and try to battle with a super rare ID 1, the possibility of victory is unlikely. Have fun!',
    
    // Farm
    'farm.title': 'Digital Farm',
    'farm.subtitle': 'Manage your digital farm and tokenize your animals',
    'farm.create': 'Create Farm',
    'farm.tokenize': 'Tokenize Animals',
    'farm.animals': 'Animals',
    'farm.tokens': 'Tokens',
    'farm.earnings': 'Earnings',
    'farm.level': 'Level',
    'farm.experience': 'Experience',
    'farm.energy': 'Energy',
    'farm.food': 'Food',
    'farm.water': 'Water',
    'farm.health': 'Health',
    'farm.happiness': 'Happiness',
    'farm.breeding': 'Breeding',
    'farm.market': 'Market',
    'farm.leaderboard': 'Leaderboard',
    'farm.achievements': 'Achievements',
    'farm.settings': 'Settings',
    'farm.help': 'Help',
    'farm.tutorial': 'Tutorial',
    'farm.guide': 'Guide',
    'farm.faq': 'FAQ',
    'farm.support': 'Support',
    'farm.contact': 'Contact',
    'farm.about': 'About',
    'farm.terms': 'Terms',
    'farm.privacy': 'Privacy',
    'farm.cookies': 'Cookies',
    'farm.language': 'Language',
    'farm.theme': 'Theme',
    'farm.sound': 'Sound',
    'farm.music': 'Music',
    'farm.effects': 'Effects',
    'farm.notifications': 'Notifications',
    'farm.email': 'Email',
    'farm.push': 'Push',
    'farm.sms': 'SMS',
    'farm.social': 'Social',
    'farm.share': 'Share',
    'farm.invite': 'Invite',
    'farm.referral': 'Referral',
    'farm.rewards': 'Rewards',
    'farm.bonus': 'Bonus',
    'farm.daily': 'Daily',
    'farm.weekly': 'Weekly',
    'farm.monthly': 'Monthly',
    'farm.special': 'Special',
    'farm.event': 'Event',
    'farm.season': 'Season',
    'farm.holiday': 'Holiday',
    'farm.anniversary': 'Anniversary',
    'farm.birthday': 'Birthday',
    'farm.celebration': 'Celebration',
    'farm.party': 'Party',
    'farm.festival': 'Festival',
    'farm.carnival': 'Carnival',
    'farm.parade': 'Parade',
    'farm.contest': 'Contest',
    'farm.competition': 'Competition',
    'farm.tournament': 'Tournament',
    'farm.championship': 'Championship',
    'farm.league': 'League',
    'farm.division': 'Division',
    'farm.rank': 'Rank',
    'farm.score': 'Score',
    'farm.points': 'Points',
    'farm.coins': 'Tokens',
    'farm.gems': 'Gems',
    'farm.crystals': 'Crystals',
    'farm.diamonds': 'Diamonds',
    'farm.gold': 'Gold',
    'farm.silver': 'Silver',
    'farm.bronze': 'Bronze',
    'farm.platinum': 'Platinum',
    'farm.titanium': 'Titanium',
    'farm.steel': 'Steel',
    'farm.iron': 'Iron',
    'farm.copper': 'Copper',
    'farm.aluminum': 'Aluminum',
    'farm.zinc': 'Zinc',
    'farm.nickel': 'Nickel',
    'farm.tin': 'Tin',
    'farm.lead': 'Lead',
    'farm.mercury': 'Mercury',
    'farm.arsenic': 'Arsenic',
    'farm.antimony': 'Antimony',
    'farm.bismuth': 'Bismuth',
    'farm.polonium': 'Polonium',
    'farm.astatine': 'Astatine',
    'farm.radon': 'Radon',
    'farm.francium': 'Francium',
    'farm.radium': 'Radium',
    'farm.actinium': 'Actinium',
    'farm.thorium': 'Thorium',
    'farm.protactinium': 'Protactinium',
    'farm.uranium': 'Uranium',
    'farm.neptunium': 'Neptunium',
    'farm.plutonium': 'Plutonium',
    'farm.americium': 'Americium',
    'farm.curium': 'Curium',
    'farm.berkelium': 'Berkelium',
    'farm.californium': 'Californium',
    'farm.einsteinium': 'Einsteinium',
    'farm.fermium': 'Fermium',
    'farm.mendelevium': 'Mendelevium',
    'farm.nobelium': 'Nobelium',
    'farm.lawrencium': 'Lawrencium',
    'farm.rutherfordium': 'Rutherfordium',
    'farm.dubnium': 'Dubnium',
    'farm.seaborgium': 'Seaborgium',
    'farm.bohrium': 'Bohrium',
    'farm.hassium': 'Hassium',
    'farm.meitnerium': 'Meitnerium',
    'farm.darmstadtium': 'Darmstadtium',
    'farm.roentgenium': 'Roentgenium',
    'farm.copernicium': 'Copernicium',
    'farm.nihonium': 'Nihonium',
    'farm.flerovium': 'Flerovium',
    'farm.moscovium': 'Moscovium',
    'farm.livermorium': 'Livermorium',
    'farm.tennessine': 'Tennessine',
    'farm.oganesson': 'Oganesson',
    
    // Farm Collection
    'farm.collection.title': 'Tokenize Your Animals',
    'farm.collection.subtitle': 'Transform your animals into unique NFTs! Create RWAnimals (Real World Animals) collections and contribute to the digital agriculture revolution. Start your journey like the Pudgy Chickens!',
    'farm.collection.info.title': 'RWAnimals Information',
    'farm.collection.name.label': 'RWAnimals Collection Name *',
    'farm.collection.name.placeholder': 'Ex: Golden Chickens from São José Farm',
    'farm.collection.description.label': 'Description *',
    'farm.collection.description.placeholder': 'Describe your RWAnimals, their unique characteristics, breed, origin and what makes them special for agriculture...',
    'farm.collection.image.label': 'RWAnimals Images Link *',
    'farm.collection.image.placeholder': 'https://example.com/animal-images',
    'farm.collection.image.help': 'Provide a link to your animal images (IPFS, Google Drive, etc.)',
    'farm.collection.region.label': 'Region *',
    'farm.collection.region.placeholder': 'Select your farm region',
    'farm.collection.type.label': 'Farm Type *',
    'farm.collection.type.placeholder': 'Select your farm type',
    'farm.collection.supply.label': 'Total NFTs',
    'farm.collection.supply.help': 'Maximum number of RWAnimals that can be tokenized in this collection',
    'farm.collection.submit': 'Tokenize RWAnimals',
    'farm.collection.submitting': 'Tokenizing RWAnimals...',
    'farm.collection.owner.title': 'Owner Information',
    'farm.collection.owner.email': 'Email',
    'farm.collection.owner.email.placeholder': 'your@email.com',
    'farm.collection.owner.name': 'Owner Name',
    'farm.collection.owner.name.placeholder': 'Your full name',
    'farm.collection.owner.farm': 'Farm Name',
    'farm.collection.owner.farm.placeholder': 'Your farm name',
    'farm.collection.preview.title': 'RWAnimals Preview',
    'farm.collection.preview.name': 'RWAnimals Name',
    'farm.collection.preview.description': 'Your animals description will appear here...',
    'farm.collection.preview.steps.title': 'Next steps:',
    'farm.collection.preview.steps.description': 'After tokenizing your RWAnimals, you will be able to upload individual images and define metadata for each animal NFT.',
    'farm.collection.success.title': 'Collection created successfully!',
    'farm.collection.success.description': 'Your collection has been created and is being processed.',
    
    // Farm Types
    'farm.type.poultry': 'Poultry',
    'farm.type.cattle': 'Cattle',
    'farm.type.agriculture': 'Agriculture',
    'farm.type.aquaculture': 'Aquaculture',
    'farm.type.mixed': 'Mixed',
    
    // Regions
    'farm.region.north': 'North',
    'farm.region.northeast': 'Northeast',
    'farm.region.centerwest': 'Center-West',
    'farm.region.southeast': 'Southeast',
    'farm.region.south': 'South',
    
    // Wallet
    'wallet.connected': 'Connected',
    'wallet.network': 'Network',
    'wallet.balance': 'Balance',
    'wallet.manage': 'Manage',
    'wallet.explorer': 'Explorer',
    'wallet.disconnect': 'Disconnect',
    'wallet.copy': 'Copy',
    'wallet.copied': 'Copied!',
    'wallet.switch': 'Switch Wallet',
    'wallet.unsupported': 'Unsupported Network',
    'wallet.error': 'Wallet Error',
    'wallet.connecting': 'Connecting...',
    'wallet.reconnecting': 'Reconnecting...',
    
    // Whitelist
    'whitelist.title': 'Request Whitelist Access',
    'whitelist.description': 'LIMITED SPOTS! Fill out the form below to secure your spot in the Pudgy Chickens whitelist.',
    'whitelist.connectWalletFirst': 'Connect your wallet first',
    'whitelist.nameRequired': 'Name is required',
    'whitelist.submittedSuccessfully': 'Request submitted successfully!',
    'whitelist.submissionError': 'Error submitting request',
    'whitelist.checkingStatus': 'Checking status...',
    'whitelist.statusTitle': 'Request Status',
    'whitelist.walletAddress': 'Wallet Address',
    'whitelist.name': 'Name',
    'whitelist.email': 'Email',
    'whitelist.twitterPost': 'Twitter Post Link',
    'whitelist.instagramPost': 'Instagram Post Link',
    'whitelist.linkedinPost': 'LinkedIn Post Link',
    'whitelist.otherSocial': 'Other Social Media',
    'whitelist.submittedAt': 'Submitted at',
    'whitelist.notes': 'Notes',
    'whitelist.pendingMessage': 'Your request is being reviewed. You will be notified when there is an update.',
    'whitelist.namePlaceholder': 'Your full name (optional)',
    'whitelist.emailPlaceholder': 'your@email.com (optional)',
    'whitelist.emailOptional': 'Email optional - used only for benefits and ecosystem information',
    'whitelist.twitterPostPlaceholder': 'https://twitter.com/user/status/...',
    'whitelist.instagramPostPlaceholder': 'https://instagram.com/p/...',
    'whitelist.linkedinPostPlaceholder': 'https://linkedin.com/posts/...',
    'whitelist.otherSocialPlaceholder': 'https://...',
    'whitelist.submit': 'Submit Request',
    'whitelist.submitting': 'Submitting...',
    'whitelist.approved': 'Approved',
    'whitelist.rejected': 'Rejected',
    'whitelist.pending': 'Pending',
    'whitelist.unknown': 'Unknown',
    'whitelist.benefits.title': 'Free Mint + Educational Course',
    'whitelist.benefits.description': 'Free mint of your real chicken NFT, access to complete smart contract development course and discount on Omnes educational products.',
    'whitelist.process.title': 'Real Project + Open Source',
    'whitelist.process.description': 'Each NFT represents a physical chicken in our farm. Smart contracts are fully open-source for learning and educational development.',
    'whitelist.community.title': 'Premium Community',
    'whitelist.community.description': 'Be part of a selected community with early access to new features and exclusive events.',
    'whitelist.backToHome': 'Back to Home',
    'whitelist.whyJoin.title': 'Why Join the Whitelist?',
    'whitelist.whyJoin.subtitle': 'LIMITED SPOTS! Discover the exclusive benefits of being part of our premium community.',
    'whitelist.suggestedMessage.title': 'Suggested Message to Share',
    'whitelist.suggestedMessage.text': 'Use this message when sharing the project on your social media:',
    'whitelist.suggestedMessage.example': 'I will participate in the world\'s first REAL chicken tokenization! 🐔 Each NFT represents a physical chicken in our farm. Educational project with open-source smart contracts by Omnes. LIMITED spots for free mint! See our farm: https://youtube.com/watch?v=HHwmYjLl8S8 🚀 #PudgyFarms #RealWorldAnimals #Tokenization #Omnes #OpenSource',
    'whitelist.lgpd.consent': 'I agree to the processing of my personal data in accordance with LGPD. The data will be used strictly for benefits and sending information about courses and products from the Pudgy Chickens ecosystem.',
    'whitelist.limitedSpots.title': 'LIMITED SPOTS',
    'whitelist.limitedSpots.description': 'Limited spots for free mint. Secure your spot now!',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.more': 'See more',
    'common.less': 'See less',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
