import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Header
    'nav.home': 'Home',
    'nav.collection': 'Coleção',
    'nav.shop': 'Loja',
    'nav.battle': 'Batalha',
    'nav.farm': 'Farm',
    'nav.community': 'Comunidade',
    'nav.connect': 'Conectar Carteira',
    
    // Hero
    'hero.title': 'Pudgy Farms',
    'hero.subtitle': 'O primeiro protocolo de tokenização de RWAnimals (Real World Animals). Começamos com as Pudgy Chickens e agora tokenizamos todos os animais da fazenda.',
    'hero.cta.primary': 'Tokenizar RWAnimals',
    'hero.cta.secondary': 'Ver Pudgy Chickens',
    'hero.stats.chickens': 'Pudgy Chickens',
    'hero.stats.tokenized': 'RWAnimals Tokenizados',
    'hero.stats.farms': 'Fazendas Globais',
    
    // Animated Section
    'gifs.title': 'GIFs da Coleção',
    'gifs.subtitle': 'Baixe e compartilhe os GIFs animados',
    
    // Collection
    'collection.title': 'Nossas Coleções',
    'collection.subtitle': 'Bem-vindo ao mundo dos Pudgy Chickens, uma plataforma nascida na web3 que promove sustentabilidade, inovação agrícola e comunidade através da tokenização de galinhas.',
    'collection.explore': 'Explorar Todas as Coleções',
    'collection.items': 'itens',
    'collection.floor': 'Floor Price',
    'collection.view': 'Ver Coleção',
    'collection.original': 'A coleção original de 10.000 galinhas únicas tokenizadas na blockchain.',
    'collection.lil': '5.000 pintinhos de descendência premium. Pequenos mas promissores.',
    
    // Shop
    'shop.title': 'Loja de Ativos',
    'shop.subtitle': 'Colecione galinhas únicas tokenizadas. Cada ativo é único e possui raridade e características especiais. Comece sua coleção hoje!',
    'shop.buy': 'Comprar',
    'shop.viewAll': 'Ver Todos os Ativos',
    'shop.reviews': 'avaliações',
    
    // Community
    'community.title': 'A Comunidade',
    'community.subtitle': 'Junte-se à família Pudgy Chicken. Um lugar onde a tecnologia encontra a agricultura, criando um futuro mais sustentável para todos!',
    'community.stats.farmers': 'Fazendeiros Ativos',
    'community.stats.farmers.desc': 'Uma comunidade global de agricultores digitais',
    'community.stats.messages': 'Mensagens/Mês',
    'community.stats.messages.desc': 'Conversas sobre agricultura sustentável',
    'community.stats.events': 'Eventos',
    'community.stats.events.desc': 'Workshops e conferências sobre tokenização',
    'community.stats.sustainability': 'Sustentabilidade',
    'community.stats.sustainability.desc': 'Promovendo agricultura responsável',
    'community.innovate': 'Inove, Participe e Cultive',
    'community.description': 'A comunidade Pudgy Chickens é mais do que apenas holders de NFT. Somos uma família global unidos pela sustentabilidade, inovação agrícola e o poder da tecnologia blockchain.',
    'community.features.workshops': 'Acesso exclusivo a workshops de agricultura',
    'community.features.decisions': 'Participe de decisões da comunidade',
    'community.features.projects': 'Colabore em projetos sustentáveis',
    'community.features.connect': 'Conecte-se com fazendeiros do mundo todo',
    'community.cta.discord': 'Entrar no Discord',
    'community.cta.twitter': 'Seguir no Twitter',
    'community.media.title': 'Pudgy Media',
    'community.media.subtitle': 'Acompanhe as últimas novidades, inovações agrícolas e conteúdo exclusivo.',
    'community.media.view': 'Ver Pudgy Media',
    
    // Footer
    'footer.description': 'Uma plataforma nascida na web3 que promove sustentabilidade, inovação agrícola e comunidade através da tokenização de galinhas.',
    'footer.collections': 'Coleções',
    'footer.shop': 'Loja',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.subtitle': 'Receba as últimas novidades sobre agricultura digital e drops exclusivos.',
    'footer.newsletter.email': 'Seu email',
    'footer.newsletter.subscribe': 'Inscrever-se',
    'footer.copyright': '© 2024 Pudgy Chickens. Todos os direitos reservados.',
    'footer.links.terms': 'Termos de Uso',
    'footer.links.privacy': 'Política de Privacidade',
    'footer.links.support': 'Suporte',
    
    // Battle
    'battle.title': 'Arena de Batalha',
    'battle.subtitle': 'Escolha seus NFTs favoritos e participe de batalhas épicas na arena. Crie uma batalha ou participe de uma existente!',
    'battle.select': 'Selecione seu NFT',
    'battle.create': 'Criar Nova Batalha',
    'battle.your': 'Suas Batalhas',
    'battle.available': 'Batalhas Disponíveis',
    'battle.none': 'Nenhuma batalha disponível',
    'battle.none.subtitle': 'Seja o primeiro a criar uma batalha e aguarde outros jogadores entrarem!',
    'battle.select.nft': 'Selecione um NFT para criar uma batalha ou participar de uma existente.',
    'battle.join': 'Entrar na Batalha',
    'battle.active': 'Batalha em andamento...',
    'battle.finished': 'Batalha Finalizada',
    'battle.winner': 'Vencedor',
    'battle.attack': 'Ataque',
    'battle.speed': 'Velocidade',
    'battle.players': 'Jogadores',
    'battle.waiting': 'Aguardando',
    'battle.your.battle': 'Sua Batalha',
    'battle.battling': 'BATALHANDO',
    'battle.victory': 'VITÓRIA!',
    'battle.winner.is': 'é o vencedor!',
    'battle.congratulations': 'Parabéns pela vitória épica!',
    'battle.select.player1': 'Selecione um NFT para o Jogador 1',
    'battle.select.player2': 'Selecione um NFT para o Jogador 2',
    'battle.waiting.opponent': 'Aguardando oponente entrar na batalha...',
    'battle.start': 'Iniciar Batalha',
    'battle.leave': 'Sair da Batalha',
    
    // Farm
    'farm.title': 'Fazenda Digital',
    'farm.subtitle': 'Gerencie sua fazenda digital e tokenize seus animais',
    'farm.create': 'Criar Fazenda',
    'farm.tokenize': 'Tokenizar Animais',
    'farm.animals': 'Animais',
    'farm.tokens': 'Tokens',
    'farm.earnings': 'Ganhos',
    'farm.level': 'Nível',
    'farm.experience': 'Experiência',
    'farm.energy': 'Energia',
    'farm.food': 'Comida',
    'farm.water': 'Água',
    'farm.health': 'Saúde',
    'farm.happiness': 'Felicidade',
    'farm.breeding': 'Reprodução',
    'farm.market': 'Mercado',
    'farm.leaderboard': 'Ranking',
    'farm.achievements': 'Conquistas',
    'farm.settings': 'Configurações',
    'farm.help': 'Ajuda',
    'farm.tutorial': 'Tutorial',
    'farm.guide': 'Guia',
    'farm.faq': 'FAQ',
    'farm.support': 'Suporte',
    'farm.contact': 'Contato',
    'farm.about': 'Sobre',
    'farm.terms': 'Termos',
    'farm.privacy': 'Privacidade',
    'farm.cookies': 'Cookies',
    'farm.language': 'Idioma',
    'farm.theme': 'Tema',
    'farm.sound': 'Som',
    'farm.music': 'Música',
    'farm.effects': 'Efeitos',
    'farm.notifications': 'Notificações',
    'farm.email': 'Email',
    'farm.push': 'Push',
    'farm.sms': 'SMS',
    'farm.social': 'Social',
    'farm.share': 'Compartilhar',
    'farm.invite': 'Convidar',
    'farm.referral': 'Indicação',
    'farm.rewards': 'Recompensas',
    'farm.bonus': 'Bônus',
    'farm.daily': 'Diário',
    'farm.weekly': 'Semanal',
    'farm.monthly': 'Mensal',
    'farm.special': 'Especial',
    'farm.event': 'Evento',
    'farm.season': 'Temporada',
    'farm.holiday': 'Feriado',
    'farm.anniversary': 'Aniversário',
    'farm.birthday': 'Aniversário',
    'farm.celebration': 'Celebração',
    'farm.party': 'Festa',
    'farm.festival': 'Festival',
    'farm.carnival': 'Carnaval',
    'farm.parade': 'Desfile',
    'farm.contest': 'Concurso',
    'farm.competition': 'Competição',
    'farm.tournament': 'Torneio',
    'farm.championship': 'Campeonato',
    'farm.league': 'Liga',
    'farm.division': 'Divisão',
    'farm.rank': 'Classificação',
    'farm.score': 'Pontuação',
    'farm.points': 'Pontos',
    'farm.coins': 'Moedas',
    'farm.gems': 'Gemas',
    'farm.crystals': 'Cristais',
    'farm.diamonds': 'Diamantes',
    'farm.gold': 'Ouro',
    'farm.silver': 'Prata',
    'farm.bronze': 'Bronze',
    'farm.platinum': 'Platina',
    'farm.titanium': 'Titânio',
    'farm.steel': 'Aço',
    'farm.iron': 'Ferro',
    'farm.copper': 'Cobre',
    'farm.aluminum': 'Alumínio',
    'farm.zinc': 'Zinco',
    'farm.nickel': 'Níquel',
    'farm.tin': 'Estanho',
    'farm.lead': 'Chumbo',
    'farm.mercury': 'Mercúrio',
    'farm.arsenic': 'Arsênio',
    'farm.antimony': 'Antimônio',
    'farm.bismuth': 'Bismuto',
    'farm.polonium': 'Polônio',
    'farm.astatine': 'Astato',
    'farm.radon': 'Radônio',
    'farm.francium': 'Frâncio',
    'farm.radium': 'Rádio',
    'farm.actinium': 'Actínio',
    'farm.thorium': 'Tório',
    'farm.protactinium': 'Protactínio',
    'farm.uranium': 'Urânio',
    'farm.neptunium': 'Netúnio',
    'farm.plutonium': 'Plutônio',
    'farm.americium': 'Amerício',
    'farm.curium': 'Cúrio',
    'farm.berkelium': 'Berquélio',
    'farm.californium': 'Califórnio',
    'farm.einsteinium': 'Einstênio',
    'farm.fermium': 'Férmio',
    'farm.mendelevium': 'Mendelévio',
    'farm.nobelium': 'Nobélio',
    'farm.lawrencium': 'Laurêncio',
    'farm.rutherfordium': 'Rutherfórdio',
    'farm.dubnium': 'Dúbnio',
    'farm.seaborgium': 'Seabórgio',
    'farm.bohrium': 'Bóhrio',
    'farm.hassium': 'Hássio',
    'farm.meitnerium': 'Meitnério',
    'farm.darmstadtium': 'Darmstádio',
    'farm.roentgenium': 'Roentgênio',
    'farm.copernicium': 'Copernício',
    'farm.nihonium': 'Nihônio',
    'farm.flerovium': 'Fleróvio',
    'farm.moscovium': 'Moscóvio',
    'farm.livermorium': 'Livermório',
    'farm.tennessine': 'Tenesso',
    'farm.oganesson': 'Oganessônio',
    
    // Farm Collection
    'farm.collection.title': 'Tokenizar Seus Animais',
    'farm.collection.subtitle': 'Transforme seus animais em NFTs únicos! Crie coleções de RWAnimals (Real World Animals) e contribua para a revolução da agricultura digital. Comece sua jornada como as Pudgy Chickens!',
    'farm.collection.info.title': 'Informações dos RWAnimals',
    'farm.collection.name.label': 'Nome da Coleção RWAnimals *',
    'farm.collection.name.placeholder': 'Ex: Galinhas Douradas da Fazenda São José',
    'farm.collection.description.label': 'Descrição *',
    'farm.collection.description.placeholder': 'Descreva seus RWAnimals, suas características únicas, raça, origem e o que os torna especiais para a agricultura...',
    'farm.collection.image.label': 'Link das Imagens dos RWAnimals *',
    'farm.collection.image.placeholder': 'https://exemplo.com/imagens-animais',
    'farm.collection.image.help': 'Forneça um link para as imagens dos seus animais (IPFS, Google Drive, etc.)',
    'farm.collection.region.label': 'Região *',
    'farm.collection.region.placeholder': 'Selecione a região da sua fazenda',
    'farm.collection.type.label': 'Tipo de Fazenda *',
    'farm.collection.type.placeholder': 'Selecione o tipo da sua fazenda',
    'farm.collection.supply.label': 'Total de NFTs',
    'farm.collection.supply.help': 'Número máximo de RWAnimals que podem ser tokenizados nesta coleção',
    'farm.collection.submit': 'Tokenizar RWAnimals',
    'farm.collection.submitting': 'Tokenizando RWAnimals...',
    'farm.collection.preview.title': 'Preview dos RWAnimals',
    'farm.collection.preview.name': 'Nome dos RWAnimals',
    'farm.collection.preview.description': 'Descrição dos seus animais aparecerá aqui...',
    'farm.collection.preview.steps.title': 'Próximos passos:',
    'farm.collection.preview.steps.description': 'Após tokenizar seus RWAnimals, você poderá fazer upload das imagens individuais e definir os metadados de cada animal NFT.',
    'farm.collection.success.title': 'Coleção criada com sucesso!',
    'farm.collection.success.description': 'Sua coleção foi criada e está sendo processada.',
    
    // Farm Types
    'farm.type.poultry': 'Avicultura',
    'farm.type.cattle': 'Pecuária',
    'farm.type.agriculture': 'Agricultura',
    'farm.type.aquaculture': 'Aquicultura',
    'farm.type.mixed': 'Mista',
    
    // Regions
    'farm.region.north': 'Norte',
    'farm.region.northeast': 'Nordeste',
    'farm.region.centerwest': 'Centro-Oeste',
    'farm.region.southeast': 'Sudeste',
    'farm.region.south': 'Sul',
    
    // Wallet
    'wallet.connected': 'Conectado',
    'wallet.network': 'Rede',
    'wallet.balance': 'Saldo',
    'wallet.manage': 'Gerenciar',
    'wallet.explorer': 'Explorer',
    'wallet.disconnect': 'Desconectar',
    'wallet.copy': 'Copiar',
    'wallet.copied': 'Copiado!',
    'wallet.switch': 'Trocar Carteira',
    'wallet.unsupported': 'Rede não suportada',
    'wallet.error': 'Erro na carteira',
    'wallet.connecting': 'Conectando...',
    'wallet.reconnecting': 'Reconectando...',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.close': 'Fechar',
    'common.save': 'Salvar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.more': 'Ver mais',
    'common.less': 'Ver menos',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.collection': 'Collection',
    'nav.shop': 'Shop',
    'nav.battle': 'Battle',
    'nav.farm': 'Farm',
    'nav.community': 'Community',
    'nav.connect': 'Connect Wallet',
    
    // Hero
    'hero.title': 'Pudgy Farms',
    'hero.subtitle': 'The first RWAnimals (Real World Animals) tokenization protocol. We started with Pudgy Chickens and now tokenize all farm animals, revolutionizing global digital agriculture.',
    'hero.cta.primary': 'Tokenize RWAnimals',
    'hero.cta.secondary': 'View Pudgy Chickens',
    'hero.stats.chickens': 'Pudgy Chickens',
    'hero.stats.tokenized': 'Tokenized RWAnimals',
    'hero.stats.farms': 'Global Farms',
    
    // Animated Section
    'gifs.title': 'Collection GIFs',
    'gifs.subtitle': 'Download and share animated GIFs',
    
    // Collection
    'collection.title': 'Our Collections',
    'collection.subtitle': 'Welcome to the world of Pudgy Chickens, a web3-born platform that promotes sustainability, agricultural innovation and community through chicken tokenization.',
    'collection.explore': 'Explore All Collections',
    'collection.items': 'items',
    'collection.floor': 'Floor Price',
    'collection.view': 'View Collection',
    'collection.original': 'The original collection of 10,000 unique chickens tokenized on the blockchain.',
    'collection.lil': '5,000 premium lineage chicks. Small but promising.',
    
    // Shop
    'shop.title': 'Asset Shop',
    'shop.subtitle': 'Collect unique tokenized chickens. Each asset is unique and has special rarity and characteristics. Start your collection today!',
    'shop.buy': 'Buy',
    'shop.viewAll': 'View All Assets',
    'shop.reviews': 'reviews',
    
    // Community
    'community.title': 'The Community',
    'community.subtitle': 'Join the Pudgy Chicken family. A place where technology meets agriculture, creating a more sustainable future for everyone!',
    'community.stats.farmers': 'Active Farmers',
    'community.stats.farmers.desc': 'A global community of digital farmers',
    'community.stats.messages': 'Messages/Month',
    'community.stats.messages.desc': 'Conversations about sustainable agriculture',
    'community.stats.events': 'Events',
    'community.stats.events.desc': 'Workshops and conferences on tokenization',
    'community.stats.sustainability': 'Sustainability',
    'community.stats.sustainability.desc': 'Promoting responsible agriculture',
    'community.innovate': 'Innovate, Participate and Cultivate',
    'community.description': 'The Pudgy Chickens community is more than just NFT holders. We are a global family united by sustainability, agricultural innovation and the power of blockchain technology.',
    'community.features.workshops': 'Exclusive access to agriculture workshops',
    'community.features.decisions': 'Participate in community decisions',
    'community.features.projects': 'Collaborate on sustainable projects',
    'community.features.connect': 'Connect with farmers from around the world',
    'community.cta.discord': 'Join Discord',
    'community.cta.twitter': 'Follow on Twitter',
    'community.media.title': 'Pudgy Media',
    'community.media.subtitle': 'Follow the latest news, agricultural innovations and exclusive content.',
    'community.media.view': 'View Pudgy Media',
    
    // Footer
    'footer.description': 'A web3-born platform that promotes sustainability, agricultural innovation and community through chicken tokenization.',
    'footer.collections': 'Collections',
    'footer.shop': 'Shop',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.subtitle': 'Receive the latest news about digital agriculture and exclusive drops.',
    'footer.newsletter.email': 'Your email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.copyright': '© 2024 Pudgy Chickens. All rights reserved.',
    'footer.links.terms': 'Terms of Use',
    'footer.links.privacy': 'Privacy Policy',
    'footer.links.support': 'Support',
    
    // Battle
    'battle.title': 'Battle Arena',
    'battle.subtitle': 'Choose your favorite NFTs and participate in epic battles in the arena. Create a battle or join an existing one!',
    'battle.select': 'Select your NFT',
    'battle.create': 'Create New Battle',
    'battle.your': 'Your Battles',
    'battle.available': 'Available Battles',
    'battle.none': 'No battles available',
    'battle.none.subtitle': 'Be the first to create a battle and wait for other players to join!',
    'battle.select.nft': 'Select an NFT to create a battle or join an existing one.',
    'battle.join': 'Join Battle',
    'battle.active': 'Battle in progress...',
    'battle.finished': 'Battle Finished',
    'battle.winner': 'Winner',
    'battle.attack': 'Attack',
    'battle.speed': 'Speed',
    'battle.players': 'Players',
    'battle.waiting': 'Waiting',
    'battle.your.battle': 'Your Battle',
    'battle.battling': 'BATTLING',
    'battle.victory': 'VICTORY!',
    'battle.winner.is': 'is the winner!',
    'battle.congratulations': 'Congratulations on the epic victory!',
    'battle.select.player1': 'Select an NFT for Player 1',
    'battle.select.player2': 'Select an NFT for Player 2',
    'battle.waiting.opponent': 'Waiting for opponent to join the battle...',
    'battle.start': 'Start Battle',
    'battle.leave': 'Leave Battle',
    
    // Farm
    'farm.title': 'Digital Farm',
    'farm.subtitle': 'Manage your digital farm and tokenize your animals',
    'farm.create': 'Create Farm',
    'farm.tokenize': 'Tokenize Animals',
    'farm.animals': 'Animals',
    'farm.tokens': 'Tokens',
    'farm.earnings': 'Earnings',
    'farm.level': 'Level',
    'farm.experience': 'Experience',
    'farm.energy': 'Energy',
    'farm.food': 'Food',
    'farm.water': 'Water',
    'farm.health': 'Health',
    'farm.happiness': 'Happiness',
    'farm.breeding': 'Breeding',
    'farm.market': 'Market',
    'farm.leaderboard': 'Leaderboard',
    'farm.achievements': 'Achievements',
    'farm.settings': 'Settings',
    'farm.help': 'Help',
    'farm.tutorial': 'Tutorial',
    'farm.guide': 'Guide',
    'farm.faq': 'FAQ',
    'farm.support': 'Support',
    'farm.contact': 'Contact',
    'farm.about': 'About',
    'farm.terms': 'Terms',
    'farm.privacy': 'Privacy',
    'farm.cookies': 'Cookies',
    'farm.language': 'Language',
    'farm.theme': 'Theme',
    'farm.sound': 'Sound',
    'farm.music': 'Music',
    'farm.effects': 'Effects',
    'farm.notifications': 'Notifications',
    'farm.email': 'Email',
    'farm.push': 'Push',
    'farm.sms': 'SMS',
    'farm.social': 'Social',
    'farm.share': 'Share',
    'farm.invite': 'Invite',
    'farm.referral': 'Referral',
    'farm.rewards': 'Rewards',
    'farm.bonus': 'Bonus',
    'farm.daily': 'Daily',
    'farm.weekly': 'Weekly',
    'farm.monthly': 'Monthly',
    'farm.special': 'Special',
    'farm.event': 'Event',
    'farm.season': 'Season',
    'farm.holiday': 'Holiday',
    'farm.anniversary': 'Anniversary',
    'farm.birthday': 'Birthday',
    'farm.celebration': 'Celebration',
    'farm.party': 'Party',
    'farm.festival': 'Festival',
    'farm.carnival': 'Carnival',
    'farm.parade': 'Parade',
    'farm.contest': 'Contest',
    'farm.competition': 'Competition',
    'farm.tournament': 'Tournament',
    'farm.championship': 'Championship',
    'farm.league': 'League',
    'farm.division': 'Division',
    'farm.rank': 'Rank',
    'farm.score': 'Score',
    'farm.points': 'Points',
    'farm.coins': 'Coins',
    'farm.gems': 'Gems',
    'farm.crystals': 'Crystals',
    'farm.diamonds': 'Diamonds',
    'farm.gold': 'Gold',
    'farm.silver': 'Silver',
    'farm.bronze': 'Bronze',
    'farm.platinum': 'Platinum',
    'farm.titanium': 'Titanium',
    'farm.steel': 'Steel',
    'farm.iron': 'Iron',
    'farm.copper': 'Copper',
    'farm.aluminum': 'Aluminum',
    'farm.zinc': 'Zinc',
    'farm.nickel': 'Nickel',
    'farm.tin': 'Tin',
    'farm.lead': 'Lead',
    'farm.mercury': 'Mercury',
    'farm.arsenic': 'Arsenic',
    'farm.antimony': 'Antimony',
    'farm.bismuth': 'Bismuth',
    'farm.polonium': 'Polonium',
    'farm.astatine': 'Astatine',
    'farm.radon': 'Radon',
    'farm.francium': 'Francium',
    'farm.radium': 'Radium',
    'farm.actinium': 'Actinium',
    'farm.thorium': 'Thorium',
    'farm.protactinium': 'Protactinium',
    'farm.uranium': 'Uranium',
    'farm.neptunium': 'Neptunium',
    'farm.plutonium': 'Plutonium',
    'farm.americium': 'Americium',
    'farm.curium': 'Curium',
    'farm.berkelium': 'Berkelium',
    'farm.californium': 'Californium',
    'farm.einsteinium': 'Einsteinium',
    'farm.fermium': 'Fermium',
    'farm.mendelevium': 'Mendelevium',
    'farm.nobelium': 'Nobelium',
    'farm.lawrencium': 'Lawrencium',
    'farm.rutherfordium': 'Rutherfordium',
    'farm.dubnium': 'Dubnium',
    'farm.seaborgium': 'Seaborgium',
    'farm.bohrium': 'Bohrium',
    'farm.hassium': 'Hassium',
    'farm.meitnerium': 'Meitnerium',
    'farm.darmstadtium': 'Darmstadtium',
    'farm.roentgenium': 'Roentgenium',
    'farm.copernicium': 'Copernicium',
    'farm.nihonium': 'Nihonium',
    'farm.flerovium': 'Flerovium',
    'farm.moscovium': 'Moscovium',
    'farm.livermorium': 'Livermorium',
    'farm.tennessine': 'Tennessine',
    'farm.oganesson': 'Oganesson',
    
    // Farm Collection
    'farm.collection.title': 'Tokenize Your Animals',
    'farm.collection.subtitle': 'Transform your animals into unique NFTs! Create RWAnimals (Real World Animals) collections and contribute to the digital agriculture revolution. Start your journey like the Pudgy Chickens!',
    'farm.collection.info.title': 'RWAnimals Information',
    'farm.collection.name.label': 'RWAnimals Collection Name *',
    'farm.collection.name.placeholder': 'Ex: Golden Chickens from São José Farm',
    'farm.collection.description.label': 'Description *',
    'farm.collection.description.placeholder': 'Describe your RWAnimals, their unique characteristics, breed, origin and what makes them special for agriculture...',
    'farm.collection.image.label': 'RWAnimals Images Link *',
    'farm.collection.image.placeholder': 'https://example.com/animal-images',
    'farm.collection.image.help': 'Provide a link to your animal images (IPFS, Google Drive, etc.)',
    'farm.collection.region.label': 'Region *',
    'farm.collection.region.placeholder': 'Select your farm region',
    'farm.collection.type.label': 'Farm Type *',
    'farm.collection.type.placeholder': 'Select your farm type',
    'farm.collection.supply.label': 'Total NFTs',
    'farm.collection.supply.help': 'Maximum number of RWAnimals that can be tokenized in this collection',
    'farm.collection.submit': 'Tokenize RWAnimals',
    'farm.collection.submitting': 'Tokenizing RWAnimals...',
    'farm.collection.preview.title': 'RWAnimals Preview',
    'farm.collection.preview.name': 'RWAnimals Name',
    'farm.collection.preview.description': 'Your animals description will appear here...',
    'farm.collection.preview.steps.title': 'Next steps:',
    'farm.collection.preview.steps.description': 'After tokenizing your RWAnimals, you will be able to upload individual images and define metadata for each animal NFT.',
    'farm.collection.success.title': 'Collection created successfully!',
    'farm.collection.success.description': 'Your collection has been created and is being processed.',
    
    // Farm Types
    'farm.type.poultry': 'Poultry',
    'farm.type.cattle': 'Cattle',
    'farm.type.agriculture': 'Agriculture',
    'farm.type.aquaculture': 'Aquaculture',
    'farm.type.mixed': 'Mixed',
    
    // Regions
    'farm.region.north': 'North',
    'farm.region.northeast': 'Northeast',
    'farm.region.centerwest': 'Center-West',
    'farm.region.southeast': 'Southeast',
    'farm.region.south': 'South',
    
    // Wallet
    'wallet.connected': 'Connected',
    'wallet.network': 'Network',
    'wallet.balance': 'Balance',
    'wallet.manage': 'Manage',
    'wallet.explorer': 'Explorer',
    'wallet.disconnect': 'Disconnect',
    'wallet.copy': 'Copy',
    'wallet.copied': 'Copied!',
    'wallet.switch': 'Switch Wallet',
    'wallet.unsupported': 'Unsupported Network',
    'wallet.error': 'Wallet Error',
    'wallet.connecting': 'Connecting...',
    'wallet.reconnecting': 'Reconnecting...',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.more': 'See more',
    'common.less': 'See less',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
